apiVersion: v1
kind: Secret
metadata:
  name: lunch-menu-secret
type: Opaque
data:
  DB_PASSWORD: ZGJfcGFzc3dvcmQ=
  JWT_SECRET: QlBGdnhzOFAwMzRkamlkRnp3cDBvYVF3MjBBbW4wSFRkaklUVDBhdThuTXNFcHBvUHJTUXdJUDdKSWNuZUxTNw==